version: '3.7'

services:

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
    expose:
      - "5432"
  
  web:
    build:
      context: .
    ports:
      - "5000:5000" 
    environment:
      - FLASK_ENV=development 
    depends_on:
      - postgres
    restart: always


volumes:
   db-data:
    driver: local
    name: alumind-bd